# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = opacity 0.9, match:class code
windowrule = opacity 0.8, match:class org.gnome.TextEditor
windowrule = opacity 0.8, match:class org.pulseaudio.pavucontrol
windowrule = opacity 0.9, match:class Simplenote
windowrule = float on,    match:title Picture in picture
windowrule = pin on,      match:title Picture in picture